import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import { Raleway } from "next/font/google";
import Navbar from "@/components/Navebr";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}  `}>
          <Navbar />
          <div className="flex mx-auto w-[90%] justify-center">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
